import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import YAML from "yaml";
const kinds = new Set(["memory", "concept", "procedure", "design"]), text = (value) => typeof value === "string" ? value.trim() : "";
export const emptyLearningTargets = () => ({ version: 1, targets: [] });
export function normalizeLearningTargets(input) { const warnings = [], source = input && typeof input === "object" ? input : {}; if (source.targets != null && !Array.isArray(source.targets)) warnings.push("targets must be an array"); const targets = (Array.isArray(source.targets) ? source.targets : []).map((target) => ({ id: text(target.id), title: text(target.title), kind: text(target.kind), origin: { episodeId: text(target.origin?.episode_id), questionIds: Array.isArray(target.origin?.question_ids) ? target.origin.question_ids.map(text).filter(Boolean) : [] }, noteRefs: Array.isArray(target.note_refs) ? target.note_refs.map(text).filter(Boolean) : [], sourceRefs: Array.isArray(target.source_refs) ? target.source_refs.map(text).filter(Boolean) : [], createdAt: target.created_at ? String(target.created_at) : null })); return { targets: { version: Number(source.version) || 1, targets }, warnings }; }
export function validateLearningTargets(model, journey = null) { const warnings = [], ids = new Set(), questions = new Map(journey?.questions.map((question) => [question.id, question]) || []), episodes = new Set(journey?.episodes.map((episode) => episode.id) || []); for (const target of model.targets) { if (!/^k\d+$/.test(target.id) || ids.has(target.id)) warnings.push(`invalid or duplicate target id: ${target.id}`); ids.add(target.id); if (!target.title || !kinds.has(target.kind)) warnings.push(`invalid target metadata: ${target.id}`); if (!target.origin.episodeId || !target.origin.questionIds.length) warnings.push(`target origin is required: ${target.id}`); if (journey && !episodes.has(target.origin.episodeId)) warnings.push(`target episode not found: ${target.id}`); for (const id of target.origin.questionIds) { const question = questions.get(id); if (journey && (!question || question.episodeId !== target.origin.episodeId)) warnings.push(`target question mismatch: ${target.id} -> ${id}`); } } return [...new Set(warnings)]; }
export function nextKnowledgeTargetId(model) { const used = new Set(model.targets.map((target) => target.id)); let number = Math.max(0, ...[...used].filter((id) => /^k\d+$/.test(id)).map((id) => Number(id.slice(1)))); do number += 1; while (used.has(`k${String(number).padStart(3, "0")}`)); return `k${String(number).padStart(3, "0")}`; }
export function createKnowledgeTarget(model, target, journey, evidence) { const questions = target.origin.questionIds.map((id) => journey.questions.find((question) => question.id === id)); if (questions.some((question) => !question || question.status !== "closed")) throw new Error("target promotion requires a closed question"); for (const question of questions) { const episode = journey.episodes.find((candidate) => candidate.id === question.episodeId), kind = episode.rootQuestionId === question.id ? "root_teach_back" : "child_connection"; if (!evidence.verifications.some((item) => item.questionId === question.id && item.kind === kind && item.result === "pass")) throw new Error("target promotion requires passing verification evidence"); } const existing = model.targets.find((candidate) => candidate.origin.questionIds.length === 1 && target.origin.questionIds.length === 1 && candidate.origin.questionIds[0] === target.origin.questionIds[0]); if (existing) return { model, target: existing }; const next = { ...model, targets: [...model.targets, target] }, warnings = validateLearningTargets(next, journey); if (warnings.length) throw new Error(`invalid learning target: ${warnings.join("; ")}`); return { model: next, target }; }
export function updateKnowledgeTarget(model, id, changes, journey) { if (!model.targets.some((target) => target.id === id)) throw new Error(`target not found: ${id}`); const next = { ...model, targets: model.targets.map((target) => target.id === id ? { ...target, title: changes.title ?? target.title, kind: changes.kind ?? target.kind, noteRefs: changes.noteRefs ?? target.noteRefs, sourceRefs: changes.sourceRefs ?? target.sourceRefs } : target) }; const warnings = validateLearningTargets(next, journey); if (warnings.length) throw new Error(`invalid learning target: ${warnings.join("; ")}`); return next; }
export function readLearningTargets(workspace) { const target = path.join(path.resolve(workspace), ".learning", "targets.yaml"); if (!existsSync(target)) return { ...normalizeLearningTargets({}), exists: false, path: target }; try { const result = normalizeLearningTargets(YAML.parse(readFileSync(target, "utf8"), { prettyErrors: true })); return { ...result, exists: true, warnings: [...result.warnings, ...validateLearningTargets(result.targets)], path: target }; } catch (error) { return { ...normalizeLearningTargets({}), exists: true, warnings: [`malformed targets.yaml: ${error.message}`], path: target }; } }
export function writeLearningTargets(workspace, model, journey = null) { const warnings = validateLearningTargets(model, journey); if (warnings.length) throw new Error(`invalid learning targets: ${warnings.join("; ")}`); const output = { version: 1, targets: model.targets.map((target) => ({ id: target.id, title: target.title, kind: target.kind, origin: { episode_id: target.origin.episodeId, question_ids: target.origin.questionIds }, note_refs: target.noteRefs, source_refs: target.sourceRefs, created_at: target.createdAt })) }; const target = path.join(path.resolve(workspace), ".learning", "targets.yaml"); mkdirSync(path.dirname(target), { recursive: true }); writeFileSync(target, YAML.stringify(output, { lineWidth: 0 })); return target; }
