import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import YAML from "yaml";
const modes = new Set(["coding", "debugging", "design"]), results = new Set(["pass", "partial", "fail"]), verificationTypes = new Set(["command", "rubric"]), text = (value) => typeof value === "string" ? value.trim() : "";
export const emptyPracticeTasks = () => ({ version: 1, tasks: [] }); export const emptyPracticeHistory = () => ({ version: 1, attempts: [] });
export function validatePracticeTasks(model, targets) { const warnings = [], ids = new Set(), targetIds = new Set(targets.targets.map((target) => target.id)); for (const task of model.tasks) { if (!/^p\d+$/.test(task.id) || ids.has(task.id)) warnings.push(`invalid or duplicate practice task id: ${task.id}`); ids.add(task.id); if (!targetIds.has(task.targetId)) warnings.push(`practice target not found: ${task.targetId}`); if (!modes.has(task.mode) || !task.title || !task.prompt || !["active", "archived"].includes(task.status) || !verificationTypes.has(task.verification.type)) warnings.push(`invalid practice task: ${task.id}`); } return [...new Set(warnings)]; }
export function validatePracticeHistory(history, tasks) { const warnings = [], ids = new Set(), byId = new Map(tasks.tasks.map((task) => [task.id, task])); for (const attempt of history.attempts) { if (!/^pa\d+$/.test(attempt.id) || ids.has(attempt.id)) warnings.push(`invalid or duplicate practice attempt id: ${attempt.id}`); ids.add(attempt.id); const task = byId.get(attempt.practiceTaskId); if (!task) warnings.push(`practice task not found: ${attempt.practiceTaskId}`); else if (task.targetId !== attempt.targetId) warnings.push(`practice attempt target mismatch: ${attempt.id}`); if (!results.has(attempt.result) || !verificationTypes.has(attempt.verification.type)) warnings.push(`invalid practice attempt: ${attempt.id}`); } return [...new Set(warnings)]; }
const read = (workspace, name, key, empty, mapper) => { const target = path.join(path.resolve(workspace), ".learning", "practice", name); if (!existsSync(target)) return { [key]: empty(), warnings: [], exists: false, path: target }; try { const source = YAML.parse(readFileSync(target, "utf8")), list = Array.isArray(source?.[key]) ? source[key] : []; return { [key]: { version: Number(source?.version) || 1, [key]: list.map(mapper) }, warnings: Array.isArray(source?.[key]) ? [] : [`${key} must be an array`], exists: true, path: target }; } catch (error) { return { [key]: empty(), warnings: [`malformed ${name}: ${error.message}`], exists: true, path: target }; } };
export const readPracticeTasks = (workspace) => read(workspace, "tasks.yaml", "tasks", emptyPracticeTasks, (item) => ({ id: text(item.id), targetId: text(item.target_id), mode: text(item.mode), title: text(item.title), prompt: text(item.prompt), verification: item.verification || {}, status: text(item.status) || "active", createdAt: item.created_at ? String(item.created_at) : null }));
export const readPracticeHistory = (workspace) => read(workspace, "history.yaml", "attempts", emptyPracticeHistory, (item) => ({ id: text(item.id), practiceTaskId: text(item.practice_task_id), targetId: text(item.target_id), result: text(item.result), verification: item.verification || {}, artifactRefs: Array.isArray(item.artifact_refs) ? item.artifact_refs.map(String) : [], evidenceId: text(item.evidence_id), createdAt: item.created_at ? String(item.created_at) : null }));
export function writePracticeTasks(workspace, model, targets) { const warnings = validatePracticeTasks(model, targets); if (warnings.length) throw new Error(warnings.join("; ")); const target = path.join(path.resolve(workspace), ".learning", "practice", "tasks.yaml"); mkdirSync(path.dirname(target), { recursive: true }); writeFileSync(target, YAML.stringify({ version: 1, tasks: model.tasks.map((item) => ({ id: item.id, target_id: item.targetId, mode: item.mode, title: item.title, prompt: item.prompt, verification: item.verification, status: item.status, created_at: item.createdAt })) }, { lineWidth: 0 })); }
export function writePracticeHistory(workspace, model, tasks) { const warnings = validatePracticeHistory(model, tasks); if (warnings.length) throw new Error(warnings.join("; ")); const target = path.join(path.resolve(workspace), ".learning", "practice", "history.yaml"); mkdirSync(path.dirname(target), { recursive: true }); writeFileSync(target, YAML.stringify({ version: 1, attempts: model.attempts.map((item) => ({ id: item.id, practice_task_id: item.practiceTaskId, target_id: item.targetId, result: item.result, verification: item.verification, artifact_refs: item.artifactRefs, evidence_id: item.evidenceId, created_at: item.createdAt })) }, { lineWidth: 0 })); }
export function nextPracticeId(items, prefix) { const used = new Set(items.map((item) => item.id)); let number = Math.max(0, ...[...used].filter((id) => new RegExp(`^${prefix}\\d+$`).test(id)).map((id) => Number(id.slice(prefix.length)))); do number += 1; while (used.has(`${prefix}${String(number).padStart(3, "0")}`)); return `${prefix}${String(number).padStart(3, "0")}`; }
