import { existsSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { writeLearningEvidence } from "./learning-evidence.mjs";
import { inspectLearningWorkspace } from "./learning-workspace.mjs";
import { emptyPracticeHistory, emptyPracticeTasks, nextPracticeId, readPracticeHistory, readPracticeTasks, validatePracticeHistory, validatePracticeTasks, writePracticeHistory, writePracticeTasks } from "./practice-domain.mjs";

export function inspectPracticeWorkspace(workspace, filter = {}) { const learning = inspectLearningWorkspace(workspace); if (learning.status !== "current") return { status: "invalid", reason: `learning workspace is ${learning.status}` }; const taskData = readPracticeTasks(workspace), historyData = readPracticeHistory(workspace), warnings = [...taskData.warnings, ...historyData.warnings, ...validatePracticeTasks(taskData.tasks, learning.targets.targets), ...validatePracticeHistory(historyData.attempts, taskData.tasks)]; let tasks = taskData.tasks.tasks.filter((task) => filter.includeArchived || task.status === "active"); if (filter.targetId) tasks = tasks.filter((task) => task.targetId === filter.targetId); const attempts = filter.targetId ? historyData.attempts.attempts.filter((attempt) => attempt.targetId === filter.targetId) : historyData.attempts.attempts; return warnings.length ? { status: "invalid", warnings } : { status: "current", tasks: { ...taskData.tasks, tasks }, history: { ...historyData.attempts, attempts }, learning, allTasks: taskData.tasks }; }
function commit(workspace, tasks, history, evidence, learning) { const stage = mkdtempSync(path.join(tmpdir(), "practice-transition-")), root = path.resolve(workspace), targets = learning.targets.targets, relative = ["practice/tasks.yaml", "practice/history.yaml", "evidence.yaml"], backups = new Map(); try { writePracticeTasks(stage, tasks, targets); writePracticeHistory(stage, history, tasks); writeLearningEvidence(stage, evidence, learning.journey.journey, targets); for (const name of relative) { const target = path.join(root, ".learning", name); backups.set(name, existsSync(target) ? readFileSync(target) : null); mkdirSync(path.dirname(target), { recursive: true }); } try { for (const name of relative) renameSync(path.join(stage, ".learning", name), path.join(root, ".learning", name)); } catch (error) { for (const [name, content] of backups) { const target = path.join(root, ".learning", name); if (content === null) rmSync(target, { force: true }); else writeFileSync(target, content); } throw error; } } finally { rmSync(stage, { recursive: true, force: true }); } }
export function executePracticeCommand(workspace, intent) { const current = inspectPracticeWorkspace(workspace, { includeArchived: true }); if (current.status !== "current") throw new Error(`practice workspace is invalid: ${current.warnings?.join("; ") || current.reason}`); const tasks = structuredClone(current.tasks), history = structuredClone(current.history), evidence = structuredClone(current.learning.evidence.evidence); if (intent.type === "create") { if (!current.learning.targets.targets.targets.some((target) => target.id === intent.targetId)) throw new Error(`target not found: ${intent.targetId}`); tasks.tasks.push({ id: nextPracticeId(tasks.tasks, "p"), targetId: intent.targetId, mode: intent.mode, title: intent.title, prompt: intent.prompt, verification: intent.verification, status: "active", createdAt: intent.createdAt }); } else if (intent.type === "record_attempt") { const task = tasks.tasks.find((candidate) => candidate.id === intent.practiceTaskId); if (!task) throw new Error(`practice task not found: ${intent.practiceTaskId}`); const attemptId = nextPracticeId(history.attempts, "pa"), evidenceId = nextPracticeId(evidence.verifications, "v"); history.attempts.push({ id: attemptId, practiceTaskId: task.id, targetId: task.targetId, result: intent.result, verification: intent.verification, artifactRefs: intent.artifactRefs || [], evidenceId, createdAt: intent.createdAt }); evidence.verifications.push({ id: evidenceId, episodeId: "", questionId: "", targetId: task.targetId, kind: "practice", result: intent.result, independence: "unaided", demonstrated: intent.result === "pass" ? [intent.verification.summary] : [], gaps: intent.result === "pass" ? [] : [intent.verification.summary], createdAt: intent.createdAt }); } else if (intent.type === "archive") { const task = tasks.tasks.find((candidate) => candidate.id === intent.practiceTaskId); if (!task) throw new Error(`practice task not found: ${intent.practiceTaskId}`); task.status = "archived"; } else throw new Error(`unknown practice command: ${intent.type}`); commit(workspace, tasks, history, evidence, current.learning); return inspectPracticeWorkspace(workspace); }
