import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import YAML from "yaml";
const modes = new Set(["recall", "explain", "transfer"]), results = new Set(["pass", "uncertain", "fail"]), independence = new Set(["unaided", "light_hint", "strong_hint"]), text = (value) => typeof value === "string" ? value.trim() : "";
export const emptyReviewItems = () => ({ version: 1, items: [] }); export const emptyReviewHistory = () => ({ version: 1, attempts: [] });
export function validateReviewItems(model, targets) { const warnings = [], ids = new Set(), targetIds = new Set(targets.targets.map((target) => target.id)); for (const item of model.items) { if (!/^r\d+$/.test(item.id) || ids.has(item.id)) warnings.push(`invalid or duplicate review item id: ${item.id}`); ids.add(item.id); if (!targetIds.has(item.targetId)) warnings.push(`review target not found: ${item.targetId}`); if (!modes.has(item.mode) || !item.prompt || item.status !== "active") warnings.push(`invalid review item: ${item.id}`); } return [...new Set(warnings)]; }
export function validateReviewHistory(history, items) { const warnings = [], ids = new Set(), byId = new Map(items.items.map((item) => [item.id, item])); for (const attempt of history.attempts) { if (!/^a\d+$/.test(attempt.id) || ids.has(attempt.id)) warnings.push(`invalid or duplicate review attempt id: ${attempt.id}`); ids.add(attempt.id); const item = byId.get(attempt.reviewItemId); if (!item) warnings.push(`review item not found: ${attempt.reviewItemId}`); else if (item.targetId !== attempt.targetId) warnings.push(`review attempt target mismatch: ${attempt.id}`); if (!results.has(attempt.result) || !independence.has(attempt.independence)) warnings.push(`invalid review attempt: ${attempt.id}`); } return [...new Set(warnings)]; }
const read = (workspace, name, empty, normalize) => { const target = path.join(path.resolve(workspace), ".learning", "review", name); if (!existsSync(target)) return { ...empty(), exists: false, path: target }; try { return { ...normalize(YAML.parse(readFileSync(target, "utf8"))), exists: true, path: target }; } catch (error) { return { ...empty(), exists: true, warnings: [`malformed ${name}: ${error.message}`], path: target }; } };
export function readReviewItems(workspace) { return read(workspace, "items.yaml", () => ({ items: emptyReviewItems(), warnings: [] }), (source) => ({ items: { version: Number(source?.version) || 1, items: (Array.isArray(source?.items) ? source.items : []).map((item) => ({ id: text(item.id), targetId: text(item.target_id), mode: text(item.mode), prompt: text(item.prompt), createdFromEvidenceId: text(item.created_from?.evidence_id) || null, status: text(item.status) || "active", createdAt: item.created_at ? String(item.created_at) : null })) }, warnings: Array.isArray(source?.items) ? [] : ["items must be an array"] })); }
export function readReviewHistory(workspace) { return read(workspace, "history.yaml", () => ({ history: emptyReviewHistory(), warnings: [] }), (source) => ({ history: { version: Number(source?.version) || 1, attempts: (Array.isArray(source?.attempts) ? source.attempts : []).map((item) => ({ id: text(item.id), reviewItemId: text(item.review_item_id), targetId: text(item.target_id), result: text(item.result), independence: text(item.independence), answerSummary: text(item.answer_summary), evidenceId: text(item.evidence_id), createdAt: item.created_at ? String(item.created_at) : null })) }, warnings: Array.isArray(source?.attempts) ? [] : ["attempts must be an array"] })); }
export function writeReviewItems(workspace, model, targets) { const warnings = validateReviewItems(model, targets); if (warnings.length) throw new Error(warnings.join("; ")); const target = path.join(path.resolve(workspace), ".learning", "review", "items.yaml"); mkdirSync(path.dirname(target), { recursive: true }); writeFileSync(target, YAML.stringify({ version: 1, items: model.items.map((item) => ({ id: item.id, target_id: item.targetId, mode: item.mode, prompt: item.prompt, created_from: item.createdFromEvidenceId ? { evidence_id: item.createdFromEvidenceId } : null, status: item.status, created_at: item.createdAt })) }, { lineWidth: 0 })); }
export function writeReviewHistory(workspace, history, items) { const warnings = validateReviewHistory(history, items); if (warnings.length) throw new Error(warnings.join("; ")); const target = path.join(path.resolve(workspace), ".learning", "review", "history.yaml"); mkdirSync(path.dirname(target), { recursive: true }); writeFileSync(target, YAML.stringify({ version: 1, attempts: history.attempts.map((item) => ({ id: item.id, review_item_id: item.reviewItemId, target_id: item.targetId, result: item.result, independence: item.independence, answer_summary: item.answerSummary, evidence_id: item.evidenceId, created_at: item.createdAt })) }, { lineWidth: 0 })); }
export function nextReviewId(items, prefix) { const used = new Set(items.map((item) => item.id)); let number = Math.max(0, ...[...used].filter((id) => new RegExp(`^${prefix}\\d+$`).test(id)).map((id) => Number(id.slice(1)))); do number += 1; while (used.has(`${prefix}${String(number).padStart(3, "0")}`)); return `${prefix}${String(number).padStart(3, "0")}`; }
