import { mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { writeLearningEvidence } from "./learning-evidence.mjs";
import { inspectLearningWorkspace } from "./learning-workspace.mjs";
import { emptyReviewHistory, emptyReviewItems, nextReviewId, readReviewHistory, readReviewItems, validateReviewHistory, validateReviewItems, writeReviewHistory, writeReviewItems } from "./review-domain.mjs";

export function inspectReviewWorkspace(workspace, filter = {}) { const learning = inspectLearningWorkspace(workspace); if (learning.status !== "current") return { status: "invalid", reason: `learning workspace is ${learning.status}`, learning }; const items = readReviewItems(workspace), historyData = readReviewHistory(workspace), warnings = [...items.warnings, ...historyData.warnings, ...validateReviewItems(items.items, learning.targets.targets), ...validateReviewHistory(historyData.history, items.items)]; const filteredItems = filter.targetId ? { ...items.items, items: items.items.items.filter((item) => item.targetId === filter.targetId) } : items.items, filteredHistory = filter.targetId ? { ...historyData.history, attempts: historyData.history.attempts.filter((attempt) => attempt.targetId === filter.targetId) } : historyData.history; return warnings.length ? { status: "invalid", warnings } : { status: "current", items: filteredItems, history: filteredHistory, learning }; }
function commit(workspace, items, history, evidence, learning) { const stage = mkdtempSync(path.join(tmpdir(), "review-transition-")), root = path.resolve(workspace), targets = learning.targets.targets; try { writeReviewItems(stage, items, targets); writeReviewHistory(stage, history, items); writeLearningEvidence(stage, evidence, learning.journey.journey, targets); const stagedItems = readReviewItems(stage), stagedHistory = readReviewHistory(stage), warnings = [...stagedItems.warnings, ...stagedHistory.warnings, ...validateReviewItems(stagedItems.items, targets), ...validateReviewHistory(stagedHistory.history, stagedItems.items)]; if (warnings.length) throw new Error(warnings.join("; ")); const relative = ["review/items.yaml", "review/history.yaml", "evidence.yaml"], backups = new Map(); for (const name of relative) { const target = path.join(root, ".learning", name); backups.set(name, existsSync(target) ? readFileSync(target) : null); mkdirSync(path.dirname(target), { recursive: true }); } try { for (const name of relative) renameSync(path.join(stage, ".learning", name), path.join(root, ".learning", name)); } catch (error) { for (const [name, content] of backups) { const target = path.join(root, ".learning", name); if (content === null) rmSync(target, { force: true }); else writeFileSync(target, content); } throw error; } } finally { rmSync(stage, { recursive: true, force: true }); } }
export function executeReviewCommand(workspace, intent) { const review = inspectReviewWorkspace(workspace); if (review.status !== "current") throw new Error(`review workspace is invalid: ${review.warnings?.join("; ") || review.reason}`); let items = structuredClone(review.items), history = structuredClone(review.history), evidence = structuredClone(review.learning.evidence.evidence); if (intent.type === "create") { if (!review.learning.targets.targets.targets.some((target) => target.id === intent.targetId)) throw new Error(`target not found: ${intent.targetId}`); items.items.push({ id: nextReviewId(items.items, "r"), targetId: intent.targetId, mode: intent.mode, prompt: intent.prompt, createdFromEvidenceId: intent.createdFromEvidenceId || null, status: "active", createdAt: intent.createdAt }); } else if (intent.type === "record_attempt") { const item = items.items.find((candidate) => candidate.id === intent.reviewItemId); if (!item) throw new Error(`review item not found: ${intent.reviewItemId}`); const attemptId = nextReviewId(history.attempts, "a"), evidenceId = nextReviewId(evidence.verifications, "v"); history.attempts.push({ id: attemptId, reviewItemId: item.id, targetId: item.targetId, result: intent.result, independence: intent.independence, answerSummary: intent.answerSummary, evidenceId, createdAt: intent.createdAt }); evidence.verifications.push({ id: evidenceId, episodeId: "", questionId: "", targetId: item.targetId, kind: "review", result: intent.result, independence: intent.independence, demonstrated: intent.result === "pass" ? [intent.answerSummary] : [], gaps: intent.result === "pass" ? [] : [intent.answerSummary], createdAt: intent.createdAt }); } else throw new Error(`unknown review command: ${intent.type}`); commit(workspace, items, history, evidence, review.learning); return inspectReviewWorkspace(workspace); }
